### ISSUE TITLE
Exception when enabling mixed-mode debugging in Visual Studio

### ISSUE THREAD

**Issue by Liangjia0411** [UnrealSharp/UnrealSharp#175]
When enabling mixed-mode debugging (debugging both C++ and C# code) in Visual Studio, it is not possible to debug C++ code(even after loading coreclr, C++code cannot be debugged); only C# code can be debugged.

**Comment by rob-ack** [comment]
I can confirm this. 
Starting debugging in mixed mode (core and native) will not load the native symbols as it seems. However im not sure if this is a U# issue rather than a VS issue.

@Liangjia0411 What exception did you see that you mentioned in the title? Make sure you use net core mode and not the net framework mode.
![image](https://github.com/user-attachments/assets/2f70fcaf-2f9a-4299-b979-55fd0ff9903c)

**Comment by Liangjia0411** [comment]
Yes,I use net core mode. But in my UEDemo that use coreclr, I change my module that `LoadingPhase` is `EarliestPossible`, the mixed mode is working correctly
